parameters:
#    sev_one_qna.example.class: SevOne\QnABundle\Example

services:

    sevone.qnabundle.q2aservice:
        class: SevOne\QnABundle\Services\Q2AService
        arguments: [ "@sevone.qnabundle.external_user" ]

    sevone.qnabundle.external_user:
        class: SevOne\QnABundle\Services\QnAExternal

    app.routing_loader:
        class: SevOne\QnABundle\Routing\AdvancedLoader
        tags:
            - { name: routing.loader }
