parameters:
#    sev_one_qna.example.class: SevOne\QnABundle\Example

services:
#    sev_one_qna.example:
#        class: %sev_one_qna.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
